server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: tiger
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.risk

logging:
  level:
    com:
      risk:
        user: debug
